#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"

test -f "$ROOT/README.md"
test -f "$ROOT/config/shared/opencode.conf"
test -f "$ROOT/config/shared/tool-versions.conf"
test -f "$ROOT/config/containers/Containerfile.wrapper"
test -f "$ROOT/config/containers/Containerfile.source-base.template"
test -f "$ROOT/config/containers/entrypoint.sh"
test -f "$ROOT/docs/shared/usage.md"
test -f "$ROOT/docs/shared/implementation-plan.md"
test -f "$ROOT/.gitignore"
test -f "$ROOT/lib/shell/common.sh"
test -f "$ROOT/tests/shared/test-all.sh"
test -f "$ROOT/tests/shared/test-common.sh"
test -f "$ROOT/tests/shared/test-runtime.sh"
test -f "$ROOT/scripts/shared/opencode-build"
test -f "$ROOT/scripts/shared/opencode-bootstrap"
test -f "$ROOT/scripts/shared/opencode-logs"
test -f "$ROOT/scripts/shared/opencode-open"
test -f "$ROOT/scripts/shared/opencode-remove"
test -f "$ROOT/scripts/shared/opencode-shell"
test -f "$ROOT/scripts/shared/opencode-start"
test -f "$ROOT/scripts/shared/opencode-status"
test -f "$ROOT/scripts/shared/opencode-stop"

grep -q '^OPENCODE_NPM_REGISTRY_BASE="https://registry.npmjs.org"$' "$ROOT/config/shared/opencode.conf"
grep -q '^OPENCODE_UBUNTU_LTS_VERSION="24.04"$' "$ROOT/config/shared/opencode.conf"
grep -q '^OPENCODE_LANE_PRODUCTION="production"$' "$ROOT/config/shared/opencode.conf"
grep -q '^OPENCODE_LANE_TEST="test"$' "$ROOT/config/shared/opencode.conf"
grep -q '^OPENCODE_MANAGED_SERVER_CONTAINER_PORT="4096"$' "$ROOT/config/shared/opencode.conf"
grep -q '^OPENCODE_TOOL_BUN_VERSION=' "$ROOT/config/shared/tool-versions.conf"
grep -q '^OPENCODE_BASE_ROOT=' "$ROOT/config/shared/opencode.conf"
grep -q '^OPENCODE_DEVELOPMENT_ROOT=' "$ROOT/config/shared/opencode.conf"
grep -q '^__pycache__/$' "$ROOT/.gitignore"
grep -q '^\.tmp/$' "$ROOT/.gitignore"
grep -q '^ARG UBUNTU_VERSION$' "$ROOT/config/containers/Containerfile.wrapper"
grep -q '^FROM ubuntu:\${UBUNTU_VERSION}$' "$ROOT/config/containers/Containerfile.wrapper"
[[ "$(grep -c '^ARG OPENCODE_CONTAINER_WORKSPACE_DIR$' "$ROOT/config/containers/Containerfile.wrapper")" == '2' ]]
[[ "$(grep -c '^ARG OPENCODE_CONTAINER_RUNTIME_HOME$' "$ROOT/config/containers/Containerfile.wrapper")" == '2' ]]
grep -q '^RUN apt-get update \\' "$ROOT/config/containers/Containerfile.wrapper"
grep -q '^  && apt-get install -y --no-install-recommends \\' "$ROOT/config/containers/Containerfile.wrapper"
! grep -q '/tmp/opencode-install-tools.sh' "$ROOT/config/containers/Containerfile.wrapper"
! grep -q '/tmp/opencode-tool-versions.conf' "$ROOT/config/containers/Containerfile.wrapper"
! grep -q 'chown -R root:root /workspace /run ' "$ROOT/config/containers/Containerfile.wrapper"
grep -q '^LABEL opencode.wrapper.lane=' "$ROOT/config/containers/Containerfile.wrapper"
grep -q '^RUN test -n "\$OPENCODE_RELEASE_ARCHIVE_URL" && test -n "\$OPENCODE_RELEASE_ARCHIVE_SHA512"' "$ROOT/config/containers/Containerfile.wrapper"
grep -q '^RUN chmod 755 /usr/local/bin/opencode-wrapper-entrypoint$' "$ROOT/config/containers/Containerfile.wrapper"
grep -q '^ENTRYPOINT \["/usr/bin/tini", "--", "/usr/local/bin/opencode-wrapper-entrypoint"\]$' "$ROOT/config/containers/Containerfile.wrapper"
grep -q 'CONTAINER_WORKSPACE_DIR="\${OPENCODE_CONTAINER_WORKSPACE_DIR:?missing OPENCODE_CONTAINER_WORKSPACE_DIR}"' "$ROOT/config/containers/entrypoint.sh"
grep -q 'RUNTIME_ENV_FILE="\${OPENCODE_WRAPPER_RUNTIME_ENV_FILE:-\$CONTAINER_RUNTIME_ENV_FILE}"' "$ROOT/config/containers/entrypoint.sh"
grep -q '^TMP_RUNTIME_ENV_FILE="\$(mktemp "\${RUNTIME_ENV_FILE}.XXXXXX")"$' "$ROOT/config/containers/entrypoint.sh"
grep -q "^printf 'export %s='" "$ROOT/config/containers/entrypoint.sh"
grep -q '^\[\[ -n "\${OPENCODE_IMAGE_NAME:-}" \]\] || fail "missing OPENCODE_IMAGE_NAME in config/shared/opencode.conf"$' "$ROOT/lib/shell/common.sh"
grep -q '^OPENCODE_LABEL_NAMESPACE="opencode.wrapper"$' "$ROOT/config/shared/opencode.conf"
grep -q '^git_has_tracking_branch() {$' "$ROOT/lib/shell/common.sh"
grep -q '^opencode_server_port_publish_spec() {$' "$ROOT/lib/shell/common.sh"
grep -q '^container_workspace_dir() {$' "$ROOT/lib/shell/common.sh"
grep -q '^workspace_names_from_base_root() {$' "$ROOT/lib/shell/common.sh"
grep -q '^resolve_workspace_argument() {$' "$ROOT/lib/shell/common.sh"
grep -q '^resolve_target_details_for_workspace() {$' "$ROOT/lib/shell/common.sh"
grep -q '^create_or_replace_container() {$' "$ROOT/lib/shell/common.sh"
grep -q '^exec_opencode_in_container() {$' "$ROOT/lib/shell/common.sh"

echo "Layout checks passed"
