#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
test -f "$ROOT/README.md"
test -f "$ROOT/config/containers/Dockerfile"
test -f "$ROOT/docs/shared/usage.md"
test -f "$ROOT/lib/shell/common.sh"
test -f "$ROOT/tests/shared/test-common.sh"
test -f "$ROOT/scripts/shared/opencode-build"
test -f "$ROOT/scripts/shared/bootstrap"
test -f "$ROOT/scripts/shared/opencode-logs"
test -f "$ROOT/scripts/shared/opencode-open"
test -f "$ROOT/scripts/shared/opencode-remove"
test -f "$ROOT/scripts/shared/opencode-shell"
test -f "$ROOT/scripts/shared/opencode-start"
test -f "$ROOT/scripts/shared/opencode-stop"
grep -q '^## Versioning$' "$ROOT/README.md"
grep -q '^## Version behaviour$' "$ROOT/docs/shared/usage.md"
grep -q '^ARG UBUNTU_VERSION=24.04$' "$ROOT/config/containers/Dockerfile"
grep -q '^FROM --platform=linux/arm64 ubuntu:\${UBUNTU_VERSION}$' "$ROOT/config/containers/Dockerfile"
grep -q '^ARG OPENCODE_VERSION=' "$ROOT/config/containers/Dockerfile"
grep -q '^OPENCODE_BASE_ROOT="\${OPENCODE_BASE_ROOT:-\$HOME/Documents/Ezirius/.applications-data/OpenCode}"$' "$ROOT/lib/shell/common.sh"
grep -q '^UBUNTU_VERSION=' "$ROOT/lib/shell/common.sh"
grep -q '^OPENCODE_VERSION=' "$ROOT/lib/shell/common.sh"
grep -q '^  echo "==> Ubuntu ver cfg:  \$UBUNTU_VERSION"$' "$ROOT/lib/shell/common.sh"
grep -q '^  echo "==> OpenCode ver cfg:\$OPENCODE_VERSION"$' "$ROOT/lib/shell/common.sh"
grep -q '^require_python3() {$' "$ROOT/lib/shell/common.sh"
grep -q '^require_arm64_host() {$' "$ROOT/lib/shell/common.sh"
grep -q '^require_workspace_name() {$' "$ROOT/lib/shell/common.sh"
grep -q '^normalize_path() {$' "$ROOT/lib/shell/common.sh"
grep -q '^expand_home_path() {$' "$ROOT/lib/shell/common.sh"
grep -q '^normalize_absolute_path() {$' "$ROOT/lib/shell/common.sh"
grep -q '^use_exec_tty() {$' "$ROOT/lib/shell/common.sh"
grep -q '^if use_exec_tty; then$' "$ROOT/scripts/shared/opencode-open"
grep -q '^if use_exec_tty; then$' "$ROOT/scripts/shared/opencode-shell"
grep -q '^"\$SCRIPT_DIR/opencode-build"$' "$ROOT/scripts/shared/bootstrap"
grep -q '^"\$SCRIPT_DIR/opencode-start" "\$WORKSPACE_INPUT"$' "$ROOT/scripts/shared/bootstrap"
grep -q '^exec "\$SCRIPT_DIR/opencode-open" "\$WORKSPACE_INPUT" "\$@"$' "$ROOT/scripts/shared/bootstrap"
grep -q '^    podman rm -f "\$CONTAINER_NAME" >/dev/null$' "$ROOT/scripts/shared/opencode-start"
grep -q '^RESOLVED_UBUNTU_VERSION="\$\(resolve_ubuntu_version\)"$' "$ROOT/scripts/shared/opencode-build"
grep -q '^RESOLVED_OPENCODE_VERSION="\$\(resolve_opencode_version\)"$' "$ROOT/scripts/shared/opencode-build"
grep -q -- '--pull=always' "$ROOT/scripts/shared/opencode-build"
grep -q -- '--platform="linux/arm64"' "$ROOT/scripts/shared/opencode-build"
grep -q -- '--platform="linux/arm64"' "$ROOT/scripts/shared/opencode-start"
grep -q '^  fail "image not found: \$OPENCODE_IMAGE_NAME (run \$SCRIPT_DIR/opencode-build first)"$' "$ROOT/scripts/shared/opencode-start"
grep -q '^    if \[\[ "\$\(container_image_id\)" == "\$\(image_id\)" \]\]; then$' "$ROOT/scripts/shared/opencode-start"
grep -q '^    echo "==> Recreating running container with updated local image: \$CONTAINER_NAME"$' "$ROOT/scripts/shared/opencode-start"
grep -q '^  elif \[\[ "\$\(container_image_id\)" != "\$\(image_id\)" \]\]; then$' "$ROOT/scripts/shared/opencode-start"

DOCKERFILE_VERSION="$(grep '^ARG OPENCODE_VERSION=' "$ROOT/config/containers/Dockerfile" | cut -d= -f2)"
test "$DOCKERFILE_VERSION" = "latest"

COMMON_SCRIPT_UBUNTU_VERSION="$(grep '^UBUNTU_VERSION=' "$ROOT/lib/shell/common.sh" | sed -E 's/.*:-([^"}]+).*/\1/')"
COMMON_SCRIPT_OPENCODE_VERSION="$(grep '^OPENCODE_VERSION=' "$ROOT/lib/shell/common.sh" | sed -E 's/.*:-([^"}]+).*/\1/')"
test "$COMMON_SCRIPT_UBUNTU_VERSION" = "latest-lts"
test "$COMMON_SCRIPT_OPENCODE_VERSION" = "latest"

echo "Layout checks passed"
