#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"

test -f "$ROOT/README.md"
test -f "$ROOT/config/shared/opencode.conf"
test -f "$ROOT/config/containers/Containerfile.wrapper"
test -f "$ROOT/config/containers/entrypoint.sh"
test -f "$ROOT/docs/shared/usage.md"
test -f "$ROOT/docs/shared/implementation-plan.md"
test -f "$ROOT/.gitignore"
test -f "$ROOT/lib/shell/common.sh"
test -f "$ROOT/tests/shared/test-all.sh"
test -f "$ROOT/tests/shared/test-common.sh"
test -f "$ROOT/tests/shared/test-runtime.sh"
test -f "$ROOT/scripts/shared/opencode-build"
test -f "$ROOT/scripts/shared/opencode-bootstrap"
test -f "$ROOT/scripts/shared/opencode-logs"
test -f "$ROOT/scripts/shared/opencode-open"
test -f "$ROOT/scripts/shared/opencode-remove"
test -f "$ROOT/scripts/shared/opencode-shell"
test -f "$ROOT/scripts/shared/opencode-start"
test -f "$ROOT/scripts/shared/opencode-status"
test -f "$ROOT/scripts/shared/opencode-stop"

grep -q '^OPENCODE_GHCR_IMAGE="ghcr.io/anomalyco/opencode"$' "$ROOT/config/shared/opencode.conf"
grep -q '^OPENCODE_BASE_ROOT=' "$ROOT/config/shared/opencode.conf"
grep -q '^__pycache__/$' "$ROOT/.gitignore"
grep -q '^\.tmp/$' "$ROOT/.gitignore"
grep -q '^ARG BASE_IMAGE$' "$ROOT/config/containers/Containerfile.wrapper"
grep -q '^LABEL opencode.wrapper.lane=' "$ROOT/config/containers/Containerfile.wrapper"
grep -q '^ENTRYPOINT \["/usr/local/bin/opencode-wrapper-entrypoint"\]$' "$ROOT/config/containers/Containerfile.wrapper"
grep -q 'RUNTIME_ENV_FILE="/tmp/opencode-wrapper-runtime.env"' "$ROOT/config/containers/entrypoint.sh"
grep -q 'CONFIG_ENV_FILE="/workspace/opencode-workspace/.config/opencode/config.env"' "$ROOT/config/containers/entrypoint.sh"
grep -q '^OPENCODE_IMAGE_NAME="\${OPENCODE_IMAGE_NAME:-opencode-local}"$' "$ROOT/lib/shell/common.sh"
grep -q '^OPENCODE_LABEL_NAMESPACE="opencode.wrapper"$' "$ROOT/lib/shell/common.sh"
grep -q '^git_has_tracking_branch() {$' "$ROOT/lib/shell/common.sh"
grep -q '^opencode_server_port_publish_spec() {$' "$ROOT/lib/shell/common.sh"
grep -q '^container_workspace_dir() {$' "$ROOT/lib/shell/common.sh"
grep -q '^resolve_target_details_for_workspace() {$' "$ROOT/lib/shell/common.sh"
grep -q '^create_or_replace_container() {$' "$ROOT/lib/shell/common.sh"
grep -q '^exec_opencode_in_container() {$' "$ROOT/lib/shell/common.sh"

echo "Layout checks passed"
