#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
test -f "$ROOT/README.md"
test -f "$ROOT/config/container/Dockerfile"
test -f "$ROOT/docs/usage.md"
test -f "$ROOT/lib/opencode/common.sh"
test -f "$ROOT/scripts/opencode-build"
test -f "$ROOT/scripts/opencode-logs"
test -f "$ROOT/scripts/opencode-open"
test -f "$ROOT/scripts/opencode-remove"
test -f "$ROOT/scripts/opencode-shell"
test -f "$ROOT/scripts/opencode-start"
test -f "$ROOT/scripts/opencode-stop"
grep -q '^FROM --platform=linux/arm64 ubuntu:24.04$' "$ROOT/config/container/Dockerfile"
grep -q '^ARG OPENCODE_VERSION=' "$ROOT/config/container/Dockerfile"
grep -q '^OPENCODE_BASE_ROOT="\${OPENCODE_BASE_ROOT:-\$HOME/Documents/OpenCode}"$' "$ROOT/lib/opencode/common.sh"
grep -q '^OPENCODE_PLATFORM=' "$ROOT/lib/opencode/common.sh"
grep -q '^OPENCODE_VERSION=' "$ROOT/lib/opencode/common.sh"

DOCKERFILE_VERSION="$(grep '^ARG OPENCODE_VERSION=' "$ROOT/config/container/Dockerfile" | cut -d= -f2)"
COMMON_SCRIPT_VERSION="$(grep '^OPENCODE_VERSION=' "$ROOT/lib/opencode/common.sh" | sed -E 's/.*:-([^"}]+).*/\1/')"
test "$DOCKERFILE_VERSION" = "$COMMON_SCRIPT_VERSION"

echo "Layout checks passed"
