#!/usr/bin/env bash

set -euo pipefail

# This test checks that the repo keeps the Hermes-style layout and command surface.

# This finds the repo root so every path check runs from the same place.
ROOT="$(cd "$(dirname "$0")/../../.." && pwd)"

# These checks prove the old legacy paths are gone.
test ! -f "$ROOT/config/shared/opencode.conf"
test ! -f "$ROOT/config/shared/tool-versions.conf"
test ! -f "$ROOT/config/containers/Containerfile.wrapper"
test ! -f "$ROOT/config/containers/Containerfile.source-base.template"
test ! -f "$ROOT/config/containers/entrypoint.sh"
test ! -f "$ROOT/docs/shared/usage.md"
test ! -f "$ROOT/docs/shared/implementation-plan.md"
test ! -f "$ROOT/lib/shell/common.sh"
test ! -f "$ROOT/scripts/shared/opencode-bootstrap"
test ! -f "$ROOT/scripts/shared/opencode-build"
test ! -f "$ROOT/scripts/shared/opencode-logs"
test ! -f "$ROOT/scripts/shared/opencode-open"
test ! -f "$ROOT/scripts/shared/opencode-remove"
test ! -f "$ROOT/scripts/shared/opencode-shell"
test ! -f "$ROOT/scripts/shared/opencode-start"
test ! -f "$ROOT/scripts/shared/opencode-status"
test ! -f "$ROOT/scripts/shared/opencode-stop"
test ! -d "$ROOT/tests/shared"

# These checks prove the normalized Hermes-style paths are present.
test -f "$ROOT/README.md"
test -f "$ROOT/AGENTS.md"
test -f "$ROOT/config/agent/shared/opencode-settings-shared.conf"
test -f "$ROOT/config/containers/shared/Containerfile"
test -f "$ROOT/docs/usage/shared/usage.md"
test -f "$ROOT/docs/usage/shared/architecture.md"
test -f "$ROOT/lib/shell/shared/common.sh"
test -f "$ROOT/scripts/agent/shared/opencode-build"
test -f "$ROOT/scripts/agent/shared/opencode-run"
test -f "$ROOT/scripts/agent/shared/opencode-shell"
test -f "$ROOT/tests/agent/shared/test-asserts.sh"
test -f "$ROOT/tests/agent/shared/test-all.sh"
test -f "$ROOT/tests/agent/shared/test-opencode-build.sh"
test -f "$ROOT/tests/agent/shared/test-opencode-layout.sh"
test -f "$ROOT/tests/agent/shared/test-opencode-run.sh"
test -f "$ROOT/tests/agent/shared/test-opencode-shell.sh"

# These checks make sure the config keeps the concrete OpenCode path contract.
grep -q '^OPENCODE_ALPINE_VERSION="' "$ROOT/config/agent/shared/opencode-settings-shared.conf"
grep -q '^OPENCODE_ALPINE_DIGEST="sha256:' "$ROOT/config/agent/shared/opencode-settings-shared.conf"
grep -q '^OPENCODE_RELEASE_LINUX_X64_ASSET="opencode-linux-x64-baseline-musl.tar.gz"$' "$ROOT/config/agent/shared/opencode-settings-shared.conf"
grep -q '^OPENCODE_RELEASE_LINUX_ARM64_ASSET="opencode-linux-arm64-musl.tar.gz"$' "$ROOT/config/agent/shared/opencode-settings-shared.conf"
grep -q '^OPENCODE_CONTAINER_HOME="/root"$' "$ROOT/config/agent/shared/opencode-settings-shared.conf"
grep -q '^OPENCODE_CONTAINER_WORKSPACE="/workspace/general"$' "$ROOT/config/agent/shared/opencode-settings-shared.conf"
grep -q '^OPENCODE_CONTAINER_DEVELOPMENT="/workspace/development"$' "$ROOT/config/agent/shared/opencode-settings-shared.conf"
grep -q '^OPENCODE_CONTAINER_PROJECT="/workspace/project"$' "$ROOT/config/agent/shared/opencode-settings-shared.conf"
grep -q '^OPENCODE_HOST_WORKSPACE_DIRNAME="opencode-general"$' "$ROOT/config/agent/shared/opencode-settings-shared.conf"
grep -q '^OPENCODE_SHELL_COMMAND="nu"$' "$ROOT/config/agent/shared/opencode-settings-shared.conf"

# These checks make sure the containerfile follows the upstream Alpine shape with wrapper additions.
grep -q '^FROM alpine:' "$ROOT/config/containers/shared/Containerfile"
grep -q '^COPY dist/opencode-linux-x64-baseline-musl/bin/opencode /usr/local/bin/opencode$' "$ROOT/config/containers/shared/Containerfile"
grep -q '^COPY dist/opencode-linux-arm64-musl/bin/opencode /usr/local/bin/opencode$' "$ROOT/config/containers/shared/Containerfile"
grep -q 'apk add .*git' "$ROOT/config/containers/shared/Containerfile"
grep -q 'apk add .*bash' "$ROOT/config/containers/shared/Containerfile"
grep -q 'apk add .*nushell' "$ROOT/config/containers/shared/Containerfile"
! grep -q '^USER ' "$ROOT/config/containers/shared/Containerfile"

# These checks make sure docs and script headers describe the current behavior.
grep -q '`scripts/agent/shared/opencode-build`' "$ROOT/README.md"
grep -q '`scripts/agent/shared/opencode-run`' "$ROOT/README.md"
grep -q '`scripts/agent/shared/opencode-shell`' "$ROOT/README.md"
grep -q '/root' "$ROOT/README.md"
grep -q 'Container user: `root`' "$ROOT/README.md"
grep -q 'wrapper convention' "$ROOT/README.md"
grep -q 'opencode-linux-x64-baseline-musl.tar.gz' "$ROOT/README.md"
grep -q 'opencode-linux-arm64-musl.tar.gz' "$ROOT/README.md"
grep -q '/workspace/general' "$ROOT/docs/usage/shared/usage.md"
grep -q '/workspace/development' "$ROOT/docs/usage/shared/usage.md"
grep -q '/workspace/project' "$ROOT/docs/usage/shared/usage.md"
grep -q '/root' "$ROOT/docs/usage/shared/usage.md"
grep -q 'When passed `--publish`, `opencode-run` publishes host port `4096 + workspace offset`' "$ROOT/docs/usage/shared/usage.md"
grep -q 'serve --hostname 0.0.0.0 --port 4096' "$ROOT/docs/usage/shared/usage.md"
grep -q 'When passed `--publish`, `opencode-run` also opens the published server URL in the default browser on macOS and Linux\.' "$ROOT/docs/usage/shared/usage.md"
grep -q 'public upstream musl CLI assets' "$ROOT/docs/usage/shared/usage.md"
grep -q 'dist/opencode-linux-x64-baseline-musl/bin/opencode' "$ROOT/docs/usage/shared/usage.md"
grep -q 'dist/opencode-linux-arm64-musl/bin/opencode' "$ROOT/docs/usage/shared/usage.md"
grep -q 'staged `-next-<pid>` replacement container' "$ROOT/docs/usage/shared/usage.md"
grep -q 'wrapper convention' "$ROOT/docs/usage/shared/architecture.md"
grep -q 'official upstream image is a minimal CLI container' "$ROOT/docs/usage/shared/architecture.md"
grep -q 'does not infer public asset names from upstream Dockerfile internals' "$ROOT/docs/usage/shared/architecture.md"
grep -q '`nu`' "$ROOT/docs/usage/shared/architecture.md"
grep -q '^# This file holds the shared shell helpers used by the wrapper scripts\.$' "$ROOT/lib/shell/shared/common.sh"
grep -q '^# This script builds a fresh OpenCode image from the saved repo settings\.$' "$ROOT/scripts/agent/shared/opencode-build"
grep -q '^# This script starts one saved workspace container and opens OpenCode inside it\.$' "$ROOT/scripts/agent/shared/opencode-run"
grep -q '^# This script opens nu by default, or runs a command inside a running workspace container\.$' "$ROOT/scripts/agent/shared/opencode-shell"

echo "OpenCode Hermes-style layout checks passed"
