#!/usr/bin/env bash

set -euo pipefail

# This test checks that the repo keeps the derived-image wrapper layout and command surface.

# This finds the repo root so every path check runs from the same place.
ROOT="$(cd "$(dirname "$0")/../../.." && pwd)"

# These checks prove the old legacy paths are gone.
test ! -f "$ROOT/config/shared/opencode.conf"
test ! -f "$ROOT/config/shared/tool-versions.conf"
test ! -f "$ROOT/config/containers/Containerfile.wrapper"
test ! -f "$ROOT/config/containers/Containerfile.source-base.template"
test ! -f "$ROOT/config/containers/entrypoint.sh"
test ! -f "$ROOT/docs/shared/usage.md"
test ! -f "$ROOT/docs/shared/implementation-plan.md"
test ! -f "$ROOT/lib/shell/common.sh"
test ! -f "$ROOT/scripts/shared/opencode-bootstrap"
test ! -f "$ROOT/scripts/shared/opencode-build"
test ! -f "$ROOT/scripts/shared/opencode-logs"
test ! -f "$ROOT/scripts/shared/opencode-open"
test ! -f "$ROOT/scripts/shared/opencode-remove"
test ! -f "$ROOT/scripts/shared/opencode-shell"
test ! -f "$ROOT/scripts/shared/opencode-start"
test ! -f "$ROOT/scripts/shared/opencode-status"
test ! -f "$ROOT/scripts/shared/opencode-stop"
test ! -d "$ROOT/tests/shared"

# These checks prove the normalized wrapper paths are present.
test -f "$ROOT/README.md"
test -f "$ROOT/AGENTS.md"
test -f "$ROOT/config/agent/shared/opencode-settings-shared.conf"
test -f "$ROOT/config/containers/shared/Containerfile"
test -f "$ROOT/docs/usage/shared/usage.md"
test -f "$ROOT/docs/usage/shared/architecture.md"
test -f "$ROOT/lib/shell/shared/common.sh"
test -f "$ROOT/scripts/agent/shared/opencode-build"
test -f "$ROOT/scripts/agent/shared/opencode-run"
test -f "$ROOT/scripts/agent/shared/opencode-shell"
test -f "$ROOT/tests/agent/shared/test-asserts.sh"
test -f "$ROOT/tests/agent/shared/test-all.sh"
test -f "$ROOT/tests/agent/shared/test-opencode-build.sh"
test -f "$ROOT/tests/agent/shared/test-opencode-layout.sh"
test -f "$ROOT/tests/agent/shared/test-opencode-run.sh"
test -f "$ROOT/tests/agent/shared/test-opencode-shell.sh"

# These checks make sure the config keeps the concrete OpenCode path contract.
grep -q '^OPENCODE_IMAGE_REPOSITORY="ghcr.io/anomalyco/opencode"$' "$ROOT/config/agent/shared/opencode-settings-shared.conf"
grep -q '^OPENCODE_VERSION="1.14.21"$' "$ROOT/config/agent/shared/opencode-settings-shared.conf"
grep -q '^OPENCODE_TARGET_ARCH="arm64"$' "$ROOT/config/agent/shared/opencode-settings-shared.conf"
grep -q '^OPENCODE_CONTAINER_HOME="/root"$' "$ROOT/config/agent/shared/opencode-settings-shared.conf"
grep -q '^OPENCODE_CONTAINER_WORKSPACE="/workspace/general"$' "$ROOT/config/agent/shared/opencode-settings-shared.conf"
grep -q '^OPENCODE_CONTAINER_DEVELOPMENT="/workspace/development"$' "$ROOT/config/agent/shared/opencode-settings-shared.conf"
grep -q '^OPENCODE_CONTAINER_PROJECTS="/workspace/projects"$' "$ROOT/config/agent/shared/opencode-settings-shared.conf"
grep -q '^OPENCODE_CONTAINER_PROJECT="/workspace/project"$' "$ROOT/config/agent/shared/opencode-settings-shared.conf"
grep -q '^OPENCODE_HOST_WORKSPACE_DIRNAME="opencode-general"$' "$ROOT/config/agent/shared/opencode-settings-shared.conf"
grep -q '^OPENCODE_SHELL_COMMAND="nu"$' "$ROOT/config/agent/shared/opencode-settings-shared.conf"

# These checks make sure the containerfile stays a thin wrapper around the official image.
grep -q '^FROM ghcr.io/anomalyco/opencode:1.14.21$' "$ROOT/config/containers/shared/Containerfile"
grep -q 'apk add --no-cache .*git' "$ROOT/config/containers/shared/Containerfile"
grep -q 'apk add --no-cache .*bash' "$ROOT/config/containers/shared/Containerfile"
grep -q 'apk add --no-cache .*nushell' "$ROOT/config/containers/shared/Containerfile"
grep -q '^WORKDIR /workspace/project$' "$ROOT/config/containers/shared/Containerfile"
grep -q '^ENTRYPOINT \["opencode"\]$' "$ROOT/config/containers/shared/Containerfile"
! grep -q '^ARG OPENCODE_ALPINE_VERSION' "$ROOT/config/containers/shared/Containerfile"
! grep -q '^COPY dist/' "$ROOT/config/containers/shared/Containerfile"
! grep -q '^USER ' "$ROOT/config/containers/shared/Containerfile"

# These checks make sure docs and script headers describe the current behavior.
grep -q '`scripts/agent/shared/opencode-build`' "$ROOT/README.md"
grep -q '`scripts/agent/shared/opencode-run`' "$ROOT/README.md"
grep -q 'scripts/agent/shared/opencode-shell <workspace> <project> \[command...\]' "$ROOT/README.md"
grep -q '/root' "$ROOT/README.md"
grep -q 'Container user: `root`' "$ROOT/README.md"
grep -q 'official upstream container' "$ROOT/README.md"
grep -q '1.14.21' "$ROOT/README.md"
grep -q 'arm64' "$ROOT/README.md"
grep -q 'Image naming: `opencode-<version>-<YYYYMMDD-HHMMSS>-<12-character-image-id>`' "$ROOT/README.md"
grep -q 'Project container naming: `opencode-<version>-<YYYYMMDD-HHMMSS>-<12-character-image-id>-<workspace>-<project>`' "$ROOT/README.md"
grep -q 'Shared runtime naming: `opencode-<version>-<YYYYMMDD-HHMMSS>-<12-character-image-id>-<workspace>-<development-root-basename>`' "$ROOT/README.md"
grep -q '/workspace/general' "$ROOT/docs/usage/shared/usage.md"
grep -q '/workspace/development' "$ROOT/docs/usage/shared/usage.md"
grep -q '/workspace/projects' "$ROOT/docs/usage/shared/usage.md"
grep -q '/workspace/project' "$ROOT/docs/usage/shared/usage.md"
grep -q '/root' "$ROOT/docs/usage/shared/usage.md"
grep -q 'shared per-workspace runtime container is running `serve --hostname 0.0.0.0 --port 4096`\.' "$ROOT/docs/usage/shared/usage.md"
grep -q 'serve --hostname 0.0.0.0 --port 4096' "$ROOT/docs/usage/shared/usage.md"
grep -q 'opens the published server URL in the default browser on macOS and Linux only when it creates or starts the shared runtime container\.' "$ROOT/docs/usage/shared/usage.md"
grep -q 'official upstream container' "$ROOT/docs/usage/shared/usage.md"
grep -q 'arm64' "$ROOT/docs/usage/shared/usage.md"
grep -q '`nu`' "$ROOT/docs/usage/shared/usage.md"
grep -q '`scripts/agent/shared/opencode-build`' "$ROOT/docs/usage/shared/usage.md"
grep -q 'Built images are named `opencode-<version>-<YYYYMMDD-HHMMSS>-<12-character-image-id>`\.' "$ROOT/docs/usage/shared/usage.md"
grep -q '`opencode-build` and `opencode-run` check the latest upstream OpenCode release before container build or run work starts\.' "$ROOT/docs/usage/shared/usage.md"
grep -q 'If a newer release exists, they warn on stderr and continue with the pinned version\.' "$ROOT/docs/usage/shared/usage.md"
grep -q 'The warning label is amber/yellow only when stderr is a terminal and `NO_COLOR` is unset; otherwise it stays plain text\.' "$ROOT/docs/usage/shared/usage.md"
grep -q 'They pause with `Press any key to continue...` only when both stdin and stderr are real terminals\.' "$ROOT/docs/usage/shared/usage.md"
grep -q 'Shared runtime containers are named `opencode-<version>-<YYYYMMDD-HHMMSS>-<12-character-image-id>-<workspace>-<development-root-basename>`\.' "$ROOT/docs/usage/shared/usage.md"
grep -q 'Project containers are named `opencode-<version>-<YYYYMMDD-HHMMSS>-<12-character-image-id>-<workspace>-<project>`\.' "$ROOT/docs/usage/shared/usage.md"
grep -q '`opencode-shell <workspace> <project>` opens `nu` by default\.' "$ROOT/docs/usage/shared/usage.md"
grep -q '`opencode-shell <workspace> -- <command...>` keeps the legacy workspace-plus-command shortcut' "$ROOT/docs/usage/shared/usage.md"
grep -q 'created directly with their final canonical names' "$ROOT/docs/usage/shared/usage.md"
grep -q 'Enter `q` to cancel selection\.' "$ROOT/docs/usage/shared/usage.md"
grep -q 'official upstream container' "$ROOT/docs/usage/shared/architecture.md"
grep -q 'thin local `Containerfile`' "$ROOT/docs/usage/shared/architecture.md"
grep -q '`nu`' "$ROOT/docs/usage/shared/architecture.md"
grep -q 'git' "$ROOT/docs/usage/shared/architecture.md"
grep -q '`opencode-build` and `opencode-run` share a best-effort pinned-version freshness check before expensive or interactive container work\.' "$ROOT/docs/usage/shared/architecture.md"
grep -q 'OpenCode release lookup failures never fail build or run\.' "$ROOT/docs/usage/shared/architecture.md"
grep -q 'Freshness warning color and pause behavior are TTY-gated so non-interactive tests and automation keep plain, non-blocking stderr\.' "$ROOT/docs/usage/shared/architecture.md"
grep -q 'shared-runtime-plus-project-container lifecycle' "$ROOT/docs/usage/shared/architecture.md"
grep -q '/workspace/projects' "$ROOT/docs/usage/shared/architecture.md"
grep -q '^# This file holds the shared shell helpers used by the wrapper scripts\.$' "$ROOT/lib/shell/shared/common.sh"
grep -q '^# This script builds a fresh OpenCode image from the saved repo settings\.$' "$ROOT/scripts/agent/shared/opencode-build"
grep -q '^# This script starts one saved workspace container and opens OpenCode inside it\.$' "$ROOT/scripts/agent/shared/opencode-run"
grep -q '^# This script opens nu by default, or runs a command inside a running workspace container\.$' "$ROOT/scripts/agent/shared/opencode-shell"

echo "OpenCode layout checks passed"
