OPENCODE_TOOL_UV_VERSION="0.11.6"
OPENCODE_TOOL_BUN_VERSION="1.3.12"
OPENCODE_TOOL_WATCHEXEC_VERSION="v2.5.1"
OPENCODE_TOOL_XH_VERSION="v0.25.3"
OPENCODE_TOOL_JJ_VERSION="v0.40.0"
OPENCODE_TOOL_WORKTRUNK_VERSION="v0.36.0"
OPENCODE_TOOL_DIVE_VERSION="v0.13.1"
OPENCODE_TOOL_SOPS_VERSION="v3.12.2"
OPENCODE_TOOL_DOGGO_VERSION="v1.1.5"
OPENCODE_TOOL_GRPCURL_VERSION="v1.9.3"
OPENCODE_TOOL_WEBSOCAT_VERSION="v1.14.1"
OPENCODE_TOOL_CSVLENS_VERSION="v0.15.1"
OPENCODE_TOOL_TLRC_VERSION="v1.13.0"

OPENCODE_TOOL_BASEDPYRIGHT_VERSION="1.39.0"
OPENCODE_TOOL_PYTEST_VERSION="9.0.3"
OPENCODE_TOOL_RUFF_VERSION="0.15.10"
OPENCODE_TOOL_PODMAN_COMPOSE_VERSION="1.5.0"
